name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libasound2-dev libbluetooth-dev libdbus-1-dev libfdk-aac-dev libglib2.0-dev libmp3lame-dev libmpg123-dev libsbc-dev libspandsp-dev
    - name: Configure and Build
      run: |
        autoreconf --install
        ./configure --enable-aac --enable-faststream --enable-mp3lame --enable-mpg123 --enable-msbc --enable-ofono --enable-upower --enable-aplay --enable-cli
        make
    - name: Publish Binary to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bluez-*.tar.gz"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
